from tkinter import *
root=Tk()
root.title('Calculator')
root.geometry('600x600')
display=Entry(root,borderwidth=5,justify='right')
display.grid(row=0, column=0, columnspan=4, padx=10, pady=10)
button_1 =Button(root,text="1",padx=5,pady=5)
button_2=Button(root,text="2",padx=5,pady=5)
button_3=Button(root,text="3",padx=5,pady=5)
button_4=Button(root,text="4",padx=5,pady=5)
button_5=Button(root,text="5",padx=5,pady=5)
button_6=Button(root,text="6",padx=5,pady=5)
button_7=Button(root,text="7",padx=5,pady=5)
button_8=Button(root,text="8",padx=5,pady=5)
button_9=Button(root,text="9",padx=5,pady=5)
button_1.grid(row=1, column=0)
button_2.grid(row=1, column=1)
button_3.grid(row=1, column=2)
button_4.grid(row=2, column=0)
button_5.grid(row=2, column=1)
button_6.grid(row=2, column=2)
button_7.grid(row=3, column=0)
button_8.grid(row=3, column=1)
button_9.grid(row=3, column=2)
root.mainloop()
