from tkinter import *
root=Tk()
root.title('Test window')
root.geometry('500x600')
l1=Label(root,text='Enter the first name:')
l2=Label(root,text='Enter the last name')
b1=Button(root,text='Terminate',width=25,command=root.destroy)
text1=Entry(root)
text2=Entry(root)
l1.grid(row=0,column=0)
l2.grid(row=1,column=0)
text1.grid(row=0,column=1)
text2.grid(row=1,column=1)
def show():
	l3=Label(root,text=f"Hello {text1.get()} {text2.get()}")
	l3.grid(row=2,column=1)
b2=Button(root,text='Click to display',command=show)
b1.grid(row=3,column=0)
b2.grid(row=4,column=0)
root.mainloop()
